import type { TileDataWithState } from "../types/tile-meta";
import type { TileSymbol } from "../types/tile-meta";
import type { LayoutPosition, GridPosition } from "../types/BoardLayouts";
import { isTileFree } from "../gameplay-features/game-logic/tile-rules";

function shuffle<T>(items: T[]): T[] {
  const next = [...items];
  for (let i = next.length - 1; i > 0; i -= 1) {
    const randomIndex = Math.floor(Math.random() * (i + 1));
    [next[i], next[randomIndex]] = [next[randomIndex], next[i]];
  }
  return next;
}

/**
 * Creates a minimal stub tile used only for blocking/free-position checks.
 * Only position data matters — symbol fields are irrelevant for geometry checks.
 */
function makeStubTile(pos: LayoutPosition): TileDataWithState {
  return {
    name: "",
    path: "",
    Component: (() => null) as TileDataWithState["Component"],
    value: "",
    isSelected: false,
    isClicked: false,
    isHighlighted: false,
    isPlayable: false,
    isMatchCandidate: false,
    isMatched: false,
    position: {
      layer: pos.layer,
      row: pos.row,
      col: pos.col,
      gridRow: 0,
      gridColumn: 0,
      offsetX: pos.offsetX,
      offsetY: pos.offsetY,
    } as GridPosition,
  };
}

/**
 * Returns true if the given position would be free (selectable) given the set of
 * remaining active positions.
 */
function isPositionFree(pos: LayoutPosition, remaining: LayoutPosition[]): boolean {
  const stub = makeStubTile(pos);
  const stubs = remaining.map(makeStubTile);
  return isTileFree(stub, stubs);
}

/**
 * Builds a guaranteed-solvable tile assignment using the backward construction
 * algorithm.
 *
 * Algorithm:
 *   1. Start with all positions active.
 *   2. Find which positions are currently "free" (unblocked on top, open on at
 *      least one side).
 *   3. Randomly pick two free positions and assign them the same tile symbol.
 *   4. Remove those positions from the active set and repeat.
 *
 * Because every assigned pair is free at the moment it is placed, a player can
 * always remove those two tiles first — guaranteeing the full board is solvable.
 */
function buildSolvableAssignment(
  positions: LayoutPosition[],
  tileData: TileSymbol[]
): TileSymbol[] {
  const assignment: (TileSymbol | null)[] = new Array(positions.length).fill(null);

  // Build one symbol per pair, then shuffle so symbols are distributed randomly.
  const pairsNeeded = Math.floor(positions.length / 2);
  const symbolsForPairs: TileSymbol[] = [];
  const shuffledData = shuffle(tileData);
  for (let i = 0; i < pairsNeeded; i++) {
    symbolsForPairs.push(shuffledData[i % shuffledData.length]);
  }
  const symbolQueue = shuffle(symbolsForPairs);
  let symbolIndex = 0;

  let remaining = positions.map((pos, index) => ({ pos, index }));

  while (remaining.length >= 2 && symbolIndex < symbolQueue.length) {
    const remainingPositions = remaining.map(({ pos }) => pos);

    const freeItems = remaining.filter(({ pos }) =>
      isPositionFree(pos, remainingPositions)
    );

    if (freeItems.length < 2) {
      // Safety fallback: the layout should always provide ≥ 2 free positions,
      // but if not, stop the guaranteed phase and fill the rest randomly.
      break;
    }

    const shuffledFree = shuffle(freeItems);
    const first = shuffledFree[0];
    const second = shuffledFree[1];

    const symbol = symbolQueue[symbolIndex++];
    assignment[first.index] = symbol;
    assignment[second.index] = symbol;

    const assigned = new Set([first.index, second.index]);
    remaining = remaining.filter(({ index }) => !assigned.has(index));
  }

  // Handle any leftover positions (odd tile count or construction fallback).
  const fallbackSymbols = shuffle(tileData);
  for (const { index } of remaining) {
    assignment[index] = fallbackSymbols[index % fallbackSymbols.length];
  }

  return assignment.map((s, i) => s ?? tileData[i % tileData.length]);
}

export function assignRandomTiles(
  positions: LayoutPosition[], // 3D positions generated by generateTurtleLayout
  tileData: TileSymbol[] // Pool of all possible tile symbols
): TileDataWithState[] {
  const assignment = buildSolvableAssignment(positions, tileData);

  return positions.map((pos, index) => {
    const symbol = assignment[index];

    if (!symbol) {
      throw new Error("Tile assignment failed: no tile symbol available for board position.");
    }

    return {
      ...symbol,
      isSelected: false,
      isClicked: false,
      isHighlighted: false,
      isPlayable: false,
      isMatchCandidate: false,
      isMatched: false,
      value: symbol.name,
      position: {
        ...pos,
        gridRow: 0, // will be computed later with layoutMapper
        gridColumn: 0,
      } as GridPosition,
    } as TileDataWithState;
  });
}
