import type { TileDataWithState } from "../types/tile-meta";
import type { TileSymbol } from "../types/tile-meta";
import type { LayoutPosition, GridPosition } from "../types/BoardLayouts";

function shuffle<T>(items: T[]): T[] {
  const next = [...items];
  for (let i = next.length - 1; i > 0; i -= 1) {
    const randomIndex = Math.floor(Math.random() * (i + 1));
    [next[i], next[randomIndex]] = [next[randomIndex], next[i]];
  }
  return next;
}

function buildBalancedPool(tileData: TileSymbol[], totalTiles: number): TileSymbol[] {
  if (tileData.length === 0 || totalTiles <= 0) return [];

  const pairsNeeded = Math.floor(totalTiles / 2);
  const pool: TileSymbol[] = [];
  let seedIndex = 0;

  while (pool.length < pairsNeeded * 2) {
    const shuffledSymbols = shuffle(tileData);
    const symbol = shuffledSymbols[seedIndex % shuffledSymbols.length];
    pool.push(symbol, symbol);
    seedIndex += 1;
  }

  if (totalTiles % 2 === 1) {
    pool.push(tileData[seedIndex % tileData.length]);
  }

  return shuffle(pool).slice(0, totalTiles);
}

export function assignRandomTiles(
  positions: LayoutPosition[], // 3D positions generated by generateTurtleLayout
  tileData: TileSymbol[] // Pool of all possible tile symbols
): TileDataWithState[] {
  const balancedPool = buildBalancedPool(tileData, positions.length);

  return positions.map((pos, index) => {
    const randomTile = balancedPool[index];

    if (!randomTile) {
      throw new Error("Tile assignment failed: no tile symbol available for board position.");
    }

    return {
      ...randomTile,
      isSelected: false,
      isClicked: false,
      isHighlighted: false,
      isPlayable: false,
      isMatchCandidate: false,
      isMatched: false,
      value: randomTile.name, // or any placeholder value
      position: {
        ...pos,
        gridRow: 0, // will be computed later with layoutMapper
        gridColumn: 0,
      } as GridPosition,
    } as TileDataWithState;
  });
}
