import type { TileDataWithState } from "../types/tile-meta";
import type { TileSymbol } from "../types/tile-meta";
import type { LayoutPosition, GridPosition } from "../types/BoardLayouts";

export function assignRandomTiles(
  positions: LayoutPosition[], // 3D positions generated by generateTurtleLayout
  tileData: TileSymbol[] // Pool of all possible tile symbols
): TileDataWithState[] {
  return positions.map(pos => {
    const randomTile = tileData[Math.floor(Math.random() * tileData.length)];
    return {
      ...randomTile,
      isSelected: false,
      isClicked: false,
      isHighlighted: false,
      value: randomTile.name, // or any placeholder value
      position: {
        ...pos,
        gridRow: 0, // will be computed later with layoutMapper
        gridColumn: 0,
      } as GridPosition,
    } as TileDataWithState;
  });
}
